services:
  postgres:
    image: postgres:16
    container_name: nyc_taxi_postgres
    environment:
      POSTGRES_USER: airflow_user
      POSTGRES_PASSWORD: airflow_pass
      POSTGRES_DB: airflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: nyc_taxi_api
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres


volumes:
  postgres_data:
